### ISSUE TITLE
原始图片数据

### ISSUE THREAD

**Issue by Be997398715** [HMTCuro/3D-Reconstruction#1]
你好，很感谢你们的工作，请问有作为第一步输入得原始图片序列数据吗？方便的话可以发出来吗，我想跑一遍你们得处理流程。非常感谢！

**Comment by HMTCuro** [comment]
感谢您的关注与支持！我们已经在Release中上传了两处建筑的原始拍摄图片，希望能够对您有所帮助。
[Release-Original Images](https://github.com/HMTCuro/3D-Reconstruction/releases/tag/5)
